ALTER TABLE clientes ADD COLUMN IF NOT EXISTS imagem_url TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS imagem_url TEXT;
ALTER TABLE rotas ADD COLUMN IF NOT EXISTS imagem_url TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS imagem_url TEXT;
